export type Vehicle = {
  name: string;
  image: string;
  dataAiHint: string;
  price: number;
  type: 'Sedan' | 'Hatchback' | 'SUV' | 'Truck' | 'MPV';
  seats: number;
  rating: number;
  reviews: number;
  useCases: string;
};

export const vehicles: Vehicle[] = [
  {
    name: 'Honda City Turbo',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'modern sedan',
    price: 856,
    type: 'Sedan',
    seats: 5,
    rating: 4.7,
    reviews: 142,
    useCases: 'เหมาะสำหรับการขับขี่ในเมืองและการเดินทางเพื่อธุรกิจ ประหยัดน้ำมันเยี่ยม',
  },
  {
    name: 'New Yaris Sport',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'red hatchback',
    price: 749,
    type: 'Hatchback',
    seats: 5,
    rating: 4.5,
    reviews: 110,
    useCases: 'ตัวเลือกที่สปอร์ตและคล่องตัวสำหรับการขับขี่ในเมืองและการเดินทางระยะสั้น',
  },
  {
    name: 'New Yaris Ativ',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'white sedan',
    price: 749,
    type: 'Sedan',
    seats: 5,
    rating: 4.6,
    reviews: 130,
    useCases: 'รถซีดานที่เชื่อถือได้และสะดวกสบายสำหรับครอบครัวและการเดินทางไกล',
  },
  {
    name: 'Nissan Almera Sportech',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'black sedan sport',
    price: 749,
    type: 'Sedan',
    seats: 5,
    rating: 4.4,
    reviews: 95,
    useCases: 'ซีดานที่มีสไตล์พร้อมความสปอร์ต เหมาะสำหรับการสร้างความประทับใจ',
  },
  {
    name: 'Suzuki CIAZ',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'grey sedan',
    price: 642,
    type: 'Sedan',
    seats: 5,
    rating: 4.3,
    reviews: 88,
    useCases: 'ตัวเลือกที่ประหยัดและกว้างขวางสำหรับนักเดินทางที่คำนึงถึงงบประมาณ',
  },
  {
    name: 'Ford Ranger Raptor',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'blue truck offroad',
    price: 1800,
    type: 'Truck',
    seats: 5,
    rating: 4.9,
    reviews: 210,
    useCases: 'สำหรับนักผจญภัยที่ต้องการสำรวจเส้นทางออฟโรด',
  },
  {
    name: 'Toyota Vigo Champ',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'silver truck pickup',
    price: 856,
    type: 'Truck',
    seats: 5,
    rating: 4.6,
    reviews: 180,
    useCases: 'รถกระบะที่แข็งแกร่งและเชื่อถือได้สำหรับการบรรทุกของหนักและการสำรวจในชนบท',
  },
  {
    name: 'Toyota Veloz',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'maroon suv family',
    price: 1070,
    type: 'SUV',
    seats: 7,
    rating: 4.7,
    reviews: 155,
    useCases: 'SUV 7 ที่นั่งที่ทันสมัย เหมาะสำหรับครอบครัวขนาดใหญ่และการเดินทางเป็นกลุ่ม',
  },
  {
    name: 'Pajero Sport Elite edition',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'white suv luxury',
    price: 1498,
    type: 'SUV',
    seats: 7,
    rating: 4.8,
    reviews: 195,
    useCases: 'ความหรูหราและสมรรถนะที่ผสมผสานกันเพื่อประสบการณ์การเดินทางระดับพรีเมียม',
  },
  {
    name: 'Mitsubishi Cross',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'orange suv compact',
    price: 1284,
    type: 'SUV',
    seats: 5,
    rating: 4.5,
    reviews: 115,
    useCases: 'SUV ขนาดกะทัดรัดอเนกประสงค์และมีสไตล์สำหรับถนนในเมืองและในชนบท',
  },
  {
    name: 'Mitsubishi Xpander',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'silver mpv',
    price: 1284,
    type: 'MPV',
    seats: 7,
    rating: 4.6,
    reviews: 140,
    useCases: 'SUV สไตล์ MPV ที่กว้างขวางและยืดหยุ่นสำหรับการเดินทางกับครอบครัวพร้อมสัมภาระมากมาย',
  },
  {
    name: 'Isuzu MU-X',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'black suv rugged',
    price: 1498,
    type: 'SUV',
    seats: 7,
    rating: 4.7,
    reviews: 170,
    useCases: 'SUV ที่แข็งแกร่งและมีความสามารถ ออกแบบมาเพื่อความสะดวกสบายในการเดินทางไกล',
  },
];
