export type Vehicle = {
  name: string;
  image: string;
  dataAiHint: string;
  price: number;
  type: 'Sedan' | 'Hatchback' | 'SUV' | 'Truck' | 'MPV';
  seats: number;
  rating: number;
  reviews: number;
  useCases: string;
};

export const vehicles: Vehicle[] = [
  {
    name: 'Honda City Turbo',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'modern sedan',
    price: 856,
    type: 'Sedan',
    seats: 5,
    rating: 4.7,
    reviews: 142,
    useCases: 'Perfect for city driving and business trips with great fuel economy.',
  },
  {
    name: 'New Yaris Sport',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'red hatchback',
    price: 749,
    type: 'Hatchback',
    seats: 5,
    rating: 4.5,
    reviews: 110,
    useCases: 'A sporty and agile choice for navigating town and short trips.',
  },
  {
    name: 'New Yaris Ativ',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'white sedan',
    price: 749,
    type: 'Sedan',
    seats: 5,
    rating: 4.6,
    reviews: 130,
    useCases: 'Reliable and comfortable sedan for families and long drives.',
  },
  {
    name: 'Nissan Almera Sportech',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'black sedan sport',
    price: 749,
    type: 'Sedan',
    seats: 5,
    rating: 4.4,
    reviews: 95,
    useCases: 'Stylish sedan with a sporty edge, ideal for making an impression.',
  },
  {
    name: 'Suzuki CIAZ',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'grey sedan',
    price: 642,
    type: 'Sedan',
    seats: 5,
    rating: 4.3,
    reviews: 88,
    useCases: 'An economical and spacious option for budget-conscious travelers.',
  },
  {
    name: 'Ford Ranger Raptor',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'blue truck offroad',
    price: 1800,
    type: 'Truck',
    seats: 5,
    rating: 4.9,
    reviews: 210,
    useCases: 'For the ultimate adventure seeker looking to explore off-road terrains.',
  },
  {
    name: 'Toyota Vigo Champ',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'silver truck pickup',
    price: 856,
    type: 'Truck',
    seats: 5,
    rating: 4.6,
    reviews: 180,
    useCases: 'A robust and dependable truck for heavy loads and rural exploration.',
  },
  {
    name: 'Toyota Veloz',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'maroon suv family',
    price: 1070,
    type: 'SUV',
    seats: 7,
    rating: 4.7,
    reviews: 155,
    useCases: 'A modern 7-seater SUV perfect for larger families and group travels.',
  },
  {
    name: 'Pajero Sport Elite edition',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'white suv luxury',
    price: 1498,
    type: 'SUV',
    seats: 7,
    rating: 4.8,
    reviews: 195,
    useCases: 'Luxury and performance combined for a premium travel experience.',
  },
  {
    name: 'Mitsubishi Cross',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'orange suv compact',
    price: 1284,
    type: 'SUV',
    seats: 5,
    rating: 4.5,
    reviews: 115,
    useCases: 'A versatile and stylish compact SUV for both city and country roads.',
  },
  {
    name: 'Mitsubishi Xpander',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'silver mpv',
    price: 1284,
    type: 'MPV',
    seats: 7,
    rating: 4.6,
    reviews: 140,
    useCases: 'Spacious and flexible MPV-style SUV for family trips with ample luggage.',
  },
  {
    name: 'Isuzu MU-X',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'black suv rugged',
    price: 1498,
    type: 'SUV',
    seats: 7,
    rating: 4.7,
    reviews: 170,
    useCases: 'A rugged and capable SUV designed for comfort on long journeys.',
  },
];
